joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

base_controller:
    type: diff_drive_controller/DiffDriveController
    left_wheel: tracks_left_joint
    right_wheel: tracks_right_joint
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000000.0]
    base_frame_id: base_link
    enable_odom_tf: false
    # This publishes an odometry message under
    # base_controller/odom
    # This odometrty isn't useful since it is too inaccurate.
    # Instead, the T265 camera gives much better odometry.

flippers_front_controller:
    type: velocity_controllers/JointVelocityController
    joint: flippers_front_joint

flippers_rear_controller:
    type: velocity_controllers/JointVelocityController
    joint: flippers_rear_joint

camera_tilt_controller:
    type: position_controllers/JointPositionController
    joint: camera_tilt_joint

arm_position_controller:
    type: position_controllers/JointGroupPositionController
    joints:
        - arm_1_joint
        - arm_2_joint
        - arm_3_joint
        - wrist_pitch_joint
        - wrist_yaw_joint
        - wrist_roll_joint

gripper_position_controller:
    type: position_controllers/JointPositionController
    joint: gripper_joint

# Moveit requires trajectory controllers in order to execute
# trajectories. Therefore, need individual joint controllers above
# and the trajectory controllers.

arm_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    action_ns: follow_joint_trajectory
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - wrist_pitch_joint
      - wrist_yaw_joint
      - wrist_roll_joint

gripper_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    action_ns: gripper_action
    joints:
      - gripper_joint
