arm_1_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_1_joint

arm_2_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_2_joint

arm_3_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_3_joint

wrist_pitch_controller:
    type: position_controllers/JointPositionController
    joint: wrist_pitch_joint

wrist_yaw_controller:
    type: position_controllers/JointPositionController
    joint: wrist_yaw_joint

wrist_roll_controller:
    type: position_controllers/JointPositionController
    joint: wrist_roll_joint

gripper_controller:
    type: position_controllers/JointPositionController
    joint: gripper_joint

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

arm_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    action_ns: follow_joint_trajectory
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - wrist_pitch_joint
      - wrist_yaw_joint
      - wrist_roll_joint

gripper_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    action_ns: gripper_action
    joints:
      - gripper_joint
