#!/usr/bin/env python

import rospy
from nav_msgs.msg import Odometry
from tf2_ros import TransformBroadcaster
from geometry_msgs.msg import TransformStamped

rospy.init_node("localisation_placeholder")

tf_broadcaster = TransformBroadcaster()
tf_msg = TransformStamped()
tf_msg.header.frame_id = "map"
tf_msg.child_frame_id = "base_link"
tf_msg.transform.rotation.w = 1

def odom_callback(msg):
    tf_msg.header.stamp = rospy.time.now()
    tf_msg.transform.translation = msg.translation
    tf_msg.transform.orientation = msg.orientation
    tf_broadcaster.send_transform(tf_msg)

odom_sub = rospy.Subscriber(
    "tracks_velocity_controller/odom", Odometry, odom_callback)

rospy.spin()
