diff_drive_controller:
    type: diff_drive_controller/DiffDriveController
    left_wheel: wheel_left
    right_wheel: wheel_right
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000000.0]
    base_frame_id: base_link
    enable_odom_tf: false

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

gazebo_ros_control:
    pid_gains:
        wheel_left: { p: 0.5, i: 0, d: 0 }
        wheel_right: { p: 0.5, i: 0, d: 0 }
