controller_list:
  - name: fake_arm_controller
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - wrist_pitch_joint
      - wrist_yaw_joint
      - wrist_roll_joint
  - name: fake_gripper_controller
    joints:
      - gripper_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: gripper
    pose: closed