# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - wrist_pitch_joint
    - wrist_yaw_joint
    - wrist_roll_joint
    - gripper_joint
    - camera_mount_joint
    - flipper_front_left_joint
    - flipper_rear_left_joint
    - tracks_left_joint
    - flipper_front_right_joint
    - flipper_rear_right_joint
    - tracks_right_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_1_controller:
  type: velocity_controllers/JointVelocityController
  joints:
    arm_1_joint
  gains:
    arm_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_2_controller:
  type: velocity_controllers/JointVelocityController
  joints:
    arm_2_joint
  gains:
    arm_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_3_controller:
  type: position_controllers/JointPositionController
  joints:
    arm_3_joint
  gains:
    arm_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
wrist_pitch_controller:
  type: position_controllers/JointPositionController
  joints:
    wrist_pitch_joint
  gains:
    wrist_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
wrist_yaw_controller:
  type: position_controllers/JointPositionController
  joints:
    wrist_yaw_joint
  gains:
    wrist_yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
wrist_roll_controller:
  type: position_controllers/JointPositionController
  joints:
    wrist_roll_joint
  gains:
    wrist_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointPositionController
  joints:
    gripper_joint
  gains:
    gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1