joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

base_controller:
    type: diff_drive_controller/DiffDriveController
    left_wheel: tracks_left_joint
    right_wheel: tracks_right_joint
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000000.0]
    base_frame_id: base_link
    enable_odom_tf: false

flippers_front_controller:
    type: effort_controllers/JointVelocityController
    joint: flippers_front_joint
    pid: {p: 400, i: 200, d: 0}

flippers_rear_controller:
    type: effort_controllers/JointVelocityController
    joint: flippers_rear_joint
    pid: {p: 400, i: 200, d: 0}

camera_tilt_controller:
    type: position_controllers/JointPositionController
    joint: camera_tilt_joint

arm_1_controller:
    type: effort_controllers/JointPositionController
    joint: arm_1_joint
    pid: {p: 100.0, i: 0, d: 1}

arm_2_controller:
    type: effort_controllers/JointPositionController
    joint: arm_2_joint
    pid: {p: 150, i: 0, d: 10}

arm_3_controller:
    type: effort_controllers/JointPositionController
    joint: arm_3_joint
    pid: {p: 150, i: 0, d: 10}

wrist_pitch_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_pitch_joint
    pid: {p: 200, i: 0, d: 1}

wrist_yaw_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_yaw_joint
    pid: {p: 100, i: 0, d: 1}

wrist_roll_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_roll_joint
    pid: {p: 10, i: 0, d: 0.1}

gripper_right_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_right_joint
    pid: {p: 0.1, i: 0, d: 0.0005}

gripper_left_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_left_joint
    pid: {p: 0.1, i: 0, d: 0.0005}

arm_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    action_ns: follow_joint_trajectory
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - wrist_pitch_joint
      - wrist_yaw_joint
      - wrist_roll_joint
    gains:
        arm_1_joint: {p: 100, i: 0, d: 1}
        arm_2_joint: {p: 150, i: 0, d: 10}
        arm_3_joint: {p: 150, i: 0, d: 10}
        wrist_pitch_joint: {p: 200, i: 0, d: 1}
        wrist_yaw_joint: {p: 100, i: 0, d: 1}
        wrist_roll_joint: {p: 10, i: 0, d: 0.1}

gripper_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    action_ns: gripper_action
    joints:
      - gripper_right_joint
      - gripper_left_joint
    gains:
        gripper_right_joint: {p: 0.1, i: 0, d: 0.0005}
        gripper_left_joint: {p: 0.1, i: 0, d: 0.0005}
