base_controller:
    type: diff_drive_controller/DiffDriveController
    left_wheel: track_left
    right_wheel: track_right
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000000.0]
    base_frame_id: base_link
    enable_odom_tf: false
