wrist_tilt_right:
    ID: 1
    Return_Delay_Time: 0
wrist_tilt_left:
    ID: 2
    Return_Delay_Time: 0
wrist_pan:
    ID: 3
    Return_Delay_Time: 0
wrist_roll:
    ID: 4
    Return_Delay_Time: 0
gripper_right:
    ID: 5
    Return_Delay_Time: 0
gripper_left:
    ID: 6
    Return_Delay_Time: 0
