# Use operating mode 1 = velocity control
arm_1:
    ID: 1
    Return_Delay_Time: 0
    Operating_Mode: 1
arm_2:
    ID: 2
    Return_Delay_Time: 0
    Operating_Mode: 1
arm_3:
    ID: 3
    Return_Delay_Time: 0
    Operating_Mode: 1
