joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

arm_controller:
    type: position_controllers/JointTrajectoryController
    default: True
    joints:
      - arm1
      - arm2
      - arm3
      - wrist1
      - wrist2
      - wrist3
