#!/usr/bin/env python

import rospy
from nav_msgs.msg import Odometry
from tf2_ros import TransformBroadcaster
from geometry_msgs.msg import TransformStamped

rospy.init_node("localisation_placeholder")

tf_broadcaster = TransformBroadcaster()
tf_msg = TransformStamped()

def odom_callback(msg):
    tf_msg.header.stamp = rospy.Time.now()
    tf_msg.transform.translation = msg.pose.pose.position
    tf_msg.transform.rotation = msg.pose.pose.orientation
    tf_msg.header.frame_id = msg.header.frame_id
    tf_msg.child_frame_id = msg.child_frame_id
    tf_broadcaster.sendTransform(tf_msg)

odom_sub = rospy.Subscriber(
    "t265/odom/sample", Odometry, odom_callback)

rospy.spin()
