arm1_controller:
    type: velocity_controllers/JointPositionController
    joint: arm1
    pid: {p: 2, i: 0, d: 0}

arm2_controller:
    type: velocity_controllers/JointPositionController
    joint: arm2
    pid: {p: 2, i: 0, d: 0}

arm3_controller:
    type: velocity_controllers/JointPositionController
    joint: arm3
    pid: {p: 2, i: 0, d: 0}

wrist_yaw_controller:
    type: position_controllers/JointPositionController
    joint: wrist_yaw

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
