arm1_controller:
    type: velocity_controllers/JointPositionController
    joint: arm1
    pid: {p: 2, i: 0, d: 0.1}

arm2_controller:
    type: velocity_controllers/JointPositionController
    joint: arm1
    pid: {p: 2, i: 0, d: 0.1}

arm3_controller:
    type: velocity_controllers/JointPositionController
    joint: arm1
    pid: {p: 2, i: 0, d: 0.1}

wrist_yaw_controller:
    type: position_controllers/JointPositionController
    joint: wrist_yaw
