# Arm: XL430-W250
# Use operating mode 1 = velocity control
arm_1:
    ID: 1
    Return_Delay_Time: 0
    Operating_Mode: 1
arm_2:
    ID: 2
    Return_Delay_Time: 0
    Operating_Mode: 1
arm_3:
    ID: 3
    Return_Delay_Time: 0
    Operating_Mode: 1

# Wrist + gripper: AX-12A
# Set CW_Angle_Limit and CCW_Angle_Limit to 0 to use wheel mode (ie: vel control)
wrist_tilt_right:
    ID: 4
    Return_Delay_Time: 0
    CW_Angle_Limit: 0
    CCW_Angle_Limit: 0
wrist_tilt_left:
    ID: 5
    Return_Delay_Time: 0
    CW_Angle_Limit: 0
    CCW_Angle_Limit: 0
wrist_pan:
    ID: 6
    Return_Delay_Time: 0
    CW_Angle_Limit: 0
    CCW_Angle_Limit: 0
wrist_roll:
    ID: 7
    Return_Delay_Time: 0
    CW_Angle_Limit: 0
    CCW_Angle_Limit: 0
gripper_right:
    ID: 8
    Return_Delay_Time: 0
    CW_Angle_Limit: 0
    CCW_Angle_Limit: 0
gripper_left:
    ID: 9
    Return_Delay_Time: 0
    CW_Angle_Limit: 0
    CCW_Angle_Limit: 0
