gazebo_ros_control:
    pid_gains:
        track_right:
            p: 100.0
            i: 0.01
            d: 10.0
        track_left:
            p: 100.0
            i: 0.01
            d: 10.0
        flippers_rear:
            p: 100.0
            i: 0.01
            d: 10.0
        flippers_front:
            p: 100.0
            i: 0.01
            d: 10.0
        arm1:
            p: 100.0
            i: 0.01
            d: 10.0
        arm2:
            p: 100.0
            i: 0.01
            d: 10.0
        arm3:
            p: 100.0
            i: 0.01
            d: 10.0
        wrist1:
            p: 100.0
            i: 0.01
            d: 10.0
        wrist2:
            p: 100.0
            i: 0.01
            d: 10.0
        wrist3:
            p: 100.0
            i: 0.01
            d: 10.0
