TrajectoryPlannerROS:
  max_vel_x: 0.8
  min_vel_x: 0
  max_vel_theta: 3
  min_vel_theta: -3
  min_in_place_vel_theta: 0.5
  latch_xy_goal_tolerance: true

  holonomic_robot: false

  meter_scoring: true

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
