obstacle_range: 2
raytrace_range: 2
footprint: [[-0.3, -0.2], [-0.3, 0.2], [0.3, 0.2], [0.3, -0.2]]
map_topic: /rtabmap/grid_map
subscribe_to_updates: true
global_frame: odom
robot_base_frame: base_link
update_frequency: 30.0
publish_frequency: 30.0
rolling_window: false

plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
# - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

static_layer:
  map_topic: /rtabmap/grid_map
  subscribe_to_updates: false

# TODO: Remove this layer or try incorporating raw realsense depth input
# obstacle_layer:
#   observation_sources: laser_scan_sensor
#   laser_scan_sensor: {
#       sensor_frame: base_scan,
#       data_type: LaserScan,
#       topic: scan,
#       marking: true,
#       clearing: true
#   }

inflation_layer:
  inflation_radius: 0.2
