controller_list:
  - name: fake_arm_controller
    joints:
      - arm1
      - arm2
      - arm3
      - wrist1
      - wrist2
      - wrist3
  - name: fake_gripper_controller
    joints:
      - wrist3
initial:  # Define initial robot poses.
  - group: arm
    pose: home